# Project: outsourcing_security_system
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = outsourcing_system_test.o programers.o 10to16.o
LINKOBJ  = outsourcing_system_test.o programers.o 10to16.o
LIBS     = -L"E:/wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/lib" -L"E:/wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc ../../../wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib/CNTL.a
INCS     = -I"E:/wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/include" -I"E:/wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/include" -I"E:/wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/wheresoftlie/Dev-c++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = outsourcing_security_system.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

outsourcing_system_test.o: outsourcing_system_test.cpp
	$(CPP) -c outsourcing_system_test.cpp -o outsourcing_system_test.o $(CXXFLAGS)

programers.o: programers.cpp
	$(CPP) -c programers.cpp -o programers.o $(CXXFLAGS)

10to16.o: 10to16.cpp
	$(CPP) -c 10to16.cpp -o 10to16.o $(CXXFLAGS)
